### ISSUE TITLE
Login with GitHub OAuth

### ISSUE THREAD

**Issue by DamienKusters** [looplanguage/api.pkg.looplang.org#7]
Separate ID is required for future use

**Comment by NealGeilen** [comment]
Requirements for this issue 

- [ ] Using the Github OAuth API
- [ ] Using a separate user Id not related to the GitHub API
- [ ] Keep in mind that other OAuth APIs can be added in the future. 
- [ ] Setting up User entity
- [ ] Setting up user roles

**Comment by DamienKusters** [comment]
Also research the use of Identity framework with MariaDB
